strict: true
site_name: "zizmor"
site_description: Static analysis for GitHub Actions
site_url: https://zizmor.sh/
docs_dir: site
site_dir: site_html
dev_addr: "127.0.0.1:9001"
repo_url: https://github.com/zizmorcore/zizmor.sh
edit_uri: edit/main/site

watch:
  - .overrides

theme:
  name: material
  custom_dir: .overrides
  logo: assets/rainbow.svg
  favicon: assets/favicon48x48.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default

      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    annotation: material/arrow-right-circle
    repo: fontawesome/brands/github

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  splash:
    image: assets/zizmor-demo.gif
    tagline: "zizmor: static analysis for GitHub Actions"
    description: |
      zizmor helps you find and fix vulnerabilities in your
      workflows and action definitions.

    button1:
      name: 🚀 Install zizmor
      url: https://docs.zizmor.sh/installation/
      theme: md-button md-button--primary

    button2:
      name: ⌛️ Quickstart
      url: https://docs.zizmor.sh/quickstart/
      theme: md-button

    button3:
      name: 📖 Audit Documentation
      url: https://docs.zizmor.sh/audits/
      theme: md-button

copyright: "&copy; 2024 William Woodruff"
